using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Attributes;
using Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Enums;
using Microsoft.OpenApi.Models;
using System.Net;

namespace Fexa.ApiClient.Function.Functions;

public class SwaggerFunctions
{
    [Function("RenderSwaggerUI")]
    [OpenApiIgnore]
    public async Task<HttpResponseData> RenderSwaggerUI(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "swagger/ui")] HttpRequestData req)
    {
        var response = req.CreateResponse(HttpStatusCode.OK);
        response.Headers.Add("Content-Type", "text/html; charset=utf-8");
        await response.WriteStringAsync(GetSwaggerUIHtml());
        return response;
    }

    [Function("RenderSwaggerDocument")]
    [OpenApiIgnore]
    public async Task<HttpResponseData> RenderSwaggerDocument(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "swagger.json")] HttpRequestData req)
    {
        var response = req.CreateResponse(HttpStatusCode.OK);
        response.Headers.Add("Content-Type", "application/json");
        
        // The OpenAPI document will be automatically generated by the OpenAPI extension
        var swaggerUrl = $"{req.Url.Scheme}://{req.Url.Host}:{req.Url.Port}/api/openapi/3.0.json";
        response.StatusCode = HttpStatusCode.PermanentRedirect;
        response.Headers.Add("Location", swaggerUrl);
        
        return response;
    }

    private static string GetSwaggerUIHtml()
    {
        return @"
<!DOCTYPE html>
<html lang=""en"">
<head>
    <meta charset=""UTF-8"">
    <title>Fexa API Middleware - Swagger UI</title>
    <link rel=""stylesheet"" type=""text/css"" href=""https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui.css"" />
    <link rel=""icon"" type=""image/png"" href=""https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/favicon-32x32.png"" sizes=""32x32"" />
    <link rel=""icon"" type=""image/png"" href=""https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/favicon-16x16.png"" sizes=""16x16"" />
    <style>
        html {
            box-sizing: border-box;
            overflow: -moz-scrollbars-vertical;
            overflow-y: scroll;
        }
        *, *:before, *:after {
            box-sizing: inherit;
        }
        body {
            margin: 0;
            background: #fafafa;
        }
    </style>
</head>
<body>
    <div id=""swagger-ui""></div>
    <script src=""https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui-bundle.js"" charset=""UTF-8""></script>
    <script src=""https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui-standalone-preset.js"" charset=""UTF-8""></script>
    <script>
        window.onload = function() {
            const ui = SwaggerUIBundle({
                url: ""/api/openapi/v2.json"",
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                layout: ""StandaloneLayout""
            });
            window.ui = ui;
        };
    </script>
</body>
</html>";
    }
}